### ISSUE TITLE
插件窗口处于无法编辑状态

### ISSUE THREAD

**Issue by NineZero517** [yangskin/SPsync#1]
当有sp文件开启时，插件窗口如果关闭，再次打开插件，插件窗口处于无法编辑状态；
复现步骤；

1. 打开SP，打开一个样本示例工程
2. 打开插件
3. 插件处于无法编辑状态
![Clip_2024-10-14_23-37-56](https://github.com/user-attachments/assets/d69d9470-914d-44bb-9043-16da8b41dc61)
逻辑好像是必须在插件加载后打开文件，插件才可以编辑。但是导致如果中途插件关闭，再次打开插件，插件也无法工作

**Comment by yangskin** [comment]
已修复

**Comment by NineZero517** [comment]
niubility
